# Generated by Django 5.1.6 on 2025-03-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_poster_recipe_poster_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="poster_id",
            new_name="poster",
        ),
    ]
