# Generated by Django 2.2.28 on 2025-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20250308_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='defaults/default_profile.png', upload_to='profile_images'),
        ),
    ]
