# Generated by Django 2.2.28 on 2025-03-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20250309_0415'),
        ('website', '0006_auto_20250308_2242'),
    ]

    operations = [
    ]
