# Generated by Django 5.1.6 on 2025-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20250308_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ImageField(blank=True, upload_to='comment_images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='defaults/default_16x10.png', upload_to='recipe_images'),
        ),
    ]
