# Generated by Django 5.1.6 on 2025-03-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20250309_0415'),
        ('website', '0007_comment_picture_recipe_picture'),
    ]

    operations = [
    ]
