# Generated by Django 5.1.6 on 2025-03-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_merge_20250315_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
