# Generated by Django 2.2.28 on 2025-03-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20250315_0650'),
        ('website', '0011_auto_20250319_1503'),
    ]

    operations = [
    ]
