# Generated by Django 5.1.6 on 2025-03-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20250321_1611'),
        ('website', '0012_merge_20250321_0533'),
    ]

    operations = [
    ]
